version: '3'
services:
  database:
    build: ./database
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  backend:
    build: ./backend
    restart: always
    links:
      - database
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PASSWORD: password
      JWT_SECRET: supersecret

  frontend:
    build: ./frontend
    image: frontend

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 8000:3000
    links:
      - backend
      - frontend
    depends_on:
      - backend
      - frontend
