INSERT INTO "categories" ("title", "sequence") VALUES ('Home', 1);
INSERT INTO "categories" ("title", "sequence") VALUES ('Loan', 2);
INSERT INTO "categories" ("title", "sequence") VALUES ('Groceries', 3);
INSERT INTO "categories" ("title", "sequence") VALUES ('Charity', 4);
INSERT INTO "categories" ("title", "sequence") VALUES ('Personal Care', 5);
INSERT INTO "categories" ("title", "sequence") VALUES ('Vacation', 6);
INSERT INTO "categories" ("title", "sequence") VALUES ('Food and Drinks', 7);
INSERT INTO "categories" ("title", "sequence") VALUES ('Transportation', 8);
INSERT INTO "categories" ("title", "sequence") VALUES ('Entertainment', 9);
INSERT INTO "categories" ("title", "sequence") VALUES ('Shopping', 10);
INSERT INTO "categories" ("title", "sequence") VALUES ('Insurance', 11);
INSERT INTO "categories" ("title", "sequence") VALUES ('Investment', 12);
INSERT INTO "categories" ("title", "sequence") VALUES ('Kids', 13);
INSERT INTO "categories" ("title", "sequence") VALUES ('Pets', 14);
INSERT INTO "categories" ("title", "sequence") VALUES ('Miscellaneous', 15);
INSERT INTO "categories" ("title", "sequence") VALUES ('Not Categorized', 16);