INSERT INTO "categories" ("title") VALUES ('Home');
INSERT INTO "categories" ("title") VALUES ('Loan');
INSERT INTO "categories" ("title") VALUES ('Groceries');
INSERT INTO "categories" ("title") VALUES ('Charity');
INSERT INTO "categories" ("title") VALUES ('Personal Care');
INSERT INTO "categories" ("title") VALUES ('Vacation');
INSERT INTO "categories" ("title") VALUES ('Food and Drinks');
INSERT INTO "categories" ("title") VALUES ('Transportation');
INSERT INTO "categories" ("title") VALUES ('Entertainment');
INSERT INTO "categories" ("title") VALUES ('Shopping');
INSERT INTO "categories" ("title") VALUES ('Insurance');
INSERT INTO "categories" ("title") VALUES ('Investment');
INSERT INTO "categories" ("title") VALUES ('Kids');
INSERT INTO "categories" ("title") VALUES ('Pets');
INSERT INTO "categories" ("title") VALUES ('Miscellaneous');
INSERT INTO "categories" ("title") VALUES ('Not Categorized');
